insert into deck values (1,"Dragon Priest Vlps",'',0,"HERO_09","id3");
insert into deck values (2,"Control Warrior Vlps",'',0,"HERO_01","id3");
insert into deck values (3,"Control Shaman Vlps",'',0,"HERO_02","id18");
insert into deck values (4,"Reno Mage Vlps",'',0,"HERO_08","id19");
insert into deck values (5,"I SEGRETI DEL MAGO",'',0,"HERO_08","id2");
insert into deck values (6,"BaRoN - LevelUP4",'',0,"HERO_01","id10");
insert into deck values (7,"BaRoN - LevelUP3",'',0,"HERO_08","id9");
insert into deck values (8,"BaRoN - LevelUP1",'',0,"HERO_09","id13");
insert into deck values (9,"RenoControl",'',0,"HERO_08","id18");
insert into deck values (10,"N\'Zoth Devolve Shaman di Savjz",'',0,"HERO_02","id15");
insert into deck values (11,"GUIDA JADE DRUID - ELEGANT",'',0,"HERO_06","id20");
insert into deck values (12,"Jade Druid dei poveri",'',0,"HERO_06","id14");
insert into deck values (13,"Shaku Miracle Rogue di SuperJJ",'',0,"HERO_03","id19");
insert into deck values (14,"Reno Mage",'',0,"HERO_08","id17");
insert into deck values (15,"Rogue ladro di giada/N\'zoth",'',0,"HERO_03","id13");
insert into deck values (16,"Jade White Shaman",'',0,"HERO_02","id4");
insert into deck values (17,"N\'toz Pala LEGGENDA",'',0,"HERO_04","id15");
insert into deck values (18,"Top100 Dragon Priest di Shoop",'',0,"HERO_09","id8");
insert into deck values (19,"Top10 Legend Aggro Jade Shaman di Amnesiac",'',0,"HERO_02","id4");
insert into deck values (20,"Aggro Pirate Warrior #25 Legend di Gameking",'',0,"HERO_01","id19");
insert into deck values (21,"Surrender Aggro Pirate Warrior #1 Legend",'',0,"HERO_01","id9");
insert into deck values (22,"Dragon Priest",'',0,"HERO_09","id2");
insert into deck values (23,"Dragon Warrior",'',0,"HERO_01","id1");
insert into deck values (24,"Token Priest",'',0,"HERO_09","id11");
insert into deck values (25,"Aggro freeze",'',0,"HERO_08","id1");
insert into deck values (26,"PalaShield by Silverdusk",'',0,"HERO_04","id20");
insert into deck values (27,"Secret Meta Crusher",'',0,"HERO_05","id13");
insert into deck values (28,"New Combo Dragon Priest",'',0,"HERO_09","id18");
insert into deck values (29,"Reno Mage di Lifecoach",'',0,"HERO_08","id12");
insert into deck values (30,"Wild Hunter",'',0,"HERO_05","id18");
insert into deck values (31,"RenoLock - Monthly Cup #4",'',0,"HERO_07","id1");
insert into deck values (32,"Thijs N\'Zoth Jade Rogue",'',0,"HERO_03","id15");
insert into deck values (33,"Anyfin Murloc Paladin di J4ckiechan",'',0,"HERO_04","id20");
insert into deck values (34,"Reno Kaza Mage di Gera89",'',0,"HERO_08","id18");
insert into deck values (35,"Jade Druid di Orange",'',0,"HERO_06","id14");
insert into deck values (36,"Reno Velen Priest di Zetalot",'',0,"HERO_09","id2");
insert into deck values (37,"Jade Shaman Legend di Loyan",'',0,"HERO_02","id7");
insert into deck values (38,"Dragon Pirate Rank 3 > Legend",'',0,"HERO_01","id3");
insert into deck values (39,"Sintolol #1 Legend Aggro Pirate Warrior",'',0,"HERO_01","id14");
insert into deck values (40,"Midrange Jade Shaman",'',0,"HERO_02","id5");
insert into deck values (41,"Jade Aggro Shaman di Orange",'',0,"HERO_02","id17");
insert into deck values (42,"PIRATI!!!! Worrior",'',0,"HERO_01","id13");
insert into deck values (43,"Hype Pala",'',0,"HERO_04","id19");
insert into deck values (44,"Dragon Velen Priest di Zetalot",'',0,"HERO_09","id16");
insert into deck values (45,"Pirate Warrior Economico",'',0,"HERO_01","id10");
insert into deck values (46,"Budget Mage",'',0,"HERO_08","id12");
insert into deck values (47,"Budget Warrior",'',0,"HERO_01","id19");
insert into deck values (48,"Budget Shaman",'',0,"HERO_02","id4");
insert into deck values (49,"Prete anti aggro budget",'',0,"HERO_09","id19");
insert into deck values (50,"Midrange Hunter Rank 5 > Rank 1 NickChipper",'',0,"HERO_05","id3");
insert into deck values (51,"Aggro Face Shaman di Zorkthar (93% Winrate)",'',0,"HERO_02","id3");
insert into deck values (52,"Taunt Warrior di Kolento",'',0,"HERO_01","id8");
insert into deck values (53,"Buff Paladin di Grimy",'',0,"HERO_04","id5");
insert into deck values (54,"Meliador\'s Small-Time Paladin",'',0,"HERO_04","id4");
insert into deck values (55,"ISPIRAZIONE DI RENO",'',0,"HERO_09","id18");
insert into deck values (56,"Savjz Reno Kazakus Dragon Priest #1 Legend",'',0,"HERO_09","id5");
insert into deck values (57,"New Aggro Hunter",'',0,"HERO_05","id3");
insert into deck values (58,"Jade Golem Gang up",'',0,"HERO_03","id11");
insert into deck values (59,"Sjow Control Priest",'',0,"HERO_09","id2");
insert into deck values (60,"Miracle Pirate Rogue Thufull",'',0,"HERO_03","id15");
insert into deck values (61,"Dragon Priest Classico",'',0,"HERO_09","id8");
insert into deck values (62,"Pirate Paladin 75% Winrate",'',0,"HERO_04","id2");
insert into deck values (63,"J4ckiechan Sacerdote Inner Fire",'',0,"HERO_09","id9");
insert into deck values (64,"Kolento Taunt Buff Warrior",'',0,"HERO_01","id8");
insert into deck values (65,"FORZA BESTIALE",'',0,"HERO_05","id20");
insert into deck values (66,"TEMPO MAGE#NO DESTAFIAMME#BY LUCA16",'',0,"HERO_08","id3");
insert into deck values (67,"Totem",'',0,"HERO_02","id9");
insert into deck values (68,"Rank 18 > 5 AL\'Akir Shaman di MantisR",'',0,"HERO_02","id7");
insert into deck values (69,"Hearts &amp",'',0,"HERO_02","id5");
insert into deck values (70,"SPELL PRIEST",'',0,"HERO_09","id2");
insert into deck values (71,"Totem Shaman (Stagione 32)",'',0,"HERO_02","id11");
insert into deck values (72,"C\'thun Warrior by Pavel",'',0,"HERO_01","id2");
insert into deck values (73,"Mrglrglmrglmrrrlggg",'',0,"HERO_04","id15");
insert into deck values (74,"OTK Malygos Hunter",'',0,"HERO_05","id10");
insert into deck values (75,"The",'',0,"HERO_09","id18");
insert into deck values (76,"Jab Top100 Dragon Priest",'',0,"HERO_09","id4");
insert into deck values (77,"Nzoth Control Druid",'',0,"HERO_06","id1");
insert into deck values (78,"Zoo Warlock Legend (Cursed)",'',0,"HERO_07","id17");
insert into deck values (79,"Guida Mago Tempo",'',0,"HERO_08","id8");
insert into deck values (80,"Guida al Secret Hunter",'',0,"HERO_05","id20");
insert into deck values (81,"Guida Miracle Rogue",'',0,"HERO_03","id19");
insert into deck values (82,"Gera89 Control Shaman C\'thun",'',0,"HERO_02","id10");
insert into deck values (83,"Aggro Paladin di Muzzy (Top10 Legend)",'',0,"HERO_04","id8");
insert into deck values (84,"Legend #11 Dragon priest di MrYagut",'',0,"HERO_09","id3");
insert into deck values (85,"Anyfin Murloc Paladin Thijs",'',0,"HERO_04","id13");
insert into deck values (86,"Cheonsu\'s Midrange Camel Hunter - Asia-Pacific Last Call",'',0,"HERO_05","id6");
insert into deck values (87,"Rank17 >> Legend in 2 giorni: Pirate Warrior",'',0,"HERO_01","id7");
insert into deck values (88,"Token Druid di Muzzy",'',0,"HERO_06","id16");
insert into deck values (89,"RDU\'s Miracle Rogue - EU Last Call 2016",'',0,"HERO_03","id16");
insert into deck values (90,"RDU\'s Discard Warlock - EU Last Call 2016",'',0,"HERO_07","id9");
insert into deck values (91,"Combo OTK Charge Warrior di HysteriA",'',0,"HERO_01","id10");
insert into deck values (92,"Tempo Mage post Nerf",'',0,"HERO_08","id3");
insert into deck values (93,"ShadowDragonPriest",'',0,"HERO_09","id11");
insert into deck values (94,"KARAZHAN MIDRANGE SHAMAN",'',0,"HERO_02","id19");
insert into deck values (95,"Giant Overlord",'',0,"HERO_02","id10");
insert into deck values (96,"Discard Warlock Zoo #1 Legend Sjow",'',0,"HERO_07","id10");
insert into deck values (97,"Rage Wolf",'',0,"HERO_01","id1");
insert into deck values (98,"N\'zoth Hunter",'',0,"HERO_05","id18");
insert into deck values (99,"Dal Rank 17 al Legend in 13 ore: Sciamano BlackDaniels",'',0,"HERO_02","id16");
insert into deck values (100,"China Autumn Championship 2016 - N\'Zoth Hunter di Ham-Shirou",'',0,"HERO_05","id6");
insert into deck values (101,"Lifecoach Secret Hunter Trucco Felino",'',0,"HERO_05","id20");
insert into deck values (102,"Thijs Yogg token Druid",'',0,"HERO_06","id7");
insert into deck values (103,"Fr0zen\'s Midrange Hunter - ONOG 2016 Pax West Finals",'',0,"HERO_05","id8");
insert into deck values (104,"Control Yogg",'',0,"HERO_09","id14");
insert into deck values (105,"Chiper Control Warrior",'',0,"HERO_01","id17");
insert into deck values (106,"Rogue di Mr Yagut con Venditrice Eterea e Pirata Festaiolo",'',0,"HERO_03","id5");
insert into deck values (107,"Mage - Budget Tempo",'',0,"HERO_08","id17");
insert into deck values (108,"PolpoZoo",'',0,"HERO_07","id18");
insert into deck values (109,"Secret Hunter Karazhan",'',0,"HERO_05","id2");
insert into deck values (110,"Malazampa Eroico",'',0,"HERO_01","id4");
insert into deck values (111,"Il Curatore Eroico",'',0,"HERO_07","id18");
insert into deck values (112,"Kripp Silence Priest Purificazione",'',0,"HERO_09","id20");
insert into deck values (113,"Sacerdote Budget Julianne Eroica",'',0,"HERO_09","id14");
insert into deck values (114,"Il Palatrino dallo Scudo Lucente",'',0,"HERO_04","id5");
insert into deck values (115,"BLOOR BASIC DECKS VIDEO - WARLOCK",'',0,"HERO_07","id2");
insert into deck values (116,"BLOOR BASIC DECKS VIDEO - PALADIN",'',0,"HERO_04","id7");
insert into deck values (117,"BLOOR BASIC DECKS VIDEO - WARRIOR",'',0,"HERO_01","id10");
insert into deck values (118,"Budget Warrior Golem dell\'Argenteria Eroico",'',0,"HERO_01","id9");
insert into deck values (119,"warlock mazzo standard",'',0,"HERO_07","id2");
insert into deck values (120,"kolento twich",'',0,"HERO_01","id5");
insert into deck values (121,"Lifecoach Tempo/Deathrattle",'',0,"HERO_03","id17");
insert into deck values (122,"N\'Zoth Freeze Mage 2.0",'',0,"HERO_08","id12");
insert into deck values (123,"Druid All Legend Deck",'',0,"HERO_06","id8");
insert into deck values (124,"Priest who steals By zodkillerx00",'',0,"HERO_09","id7");
insert into deck values (125,"Guida MidRange Hunter",'',0,"HERO_05","id10");
insert into deck values (126,"PURPLE’S ANYFIN MURLOC PALADIN (JULY 2016, SEASON 28)",'',0,"HERO_04","id17");
insert into deck values (127,"Garrim FaceShaman",'',0,"HERO_02","id17");
insert into deck values (128,"Chakki Top 10 Legend Aggro Beast Druid S27",'',0,"HERO_06","id11");
insert into deck values (129,"Mattiux Dragon Priest",'',0,"HERO_09","id14");
insert into deck values (130,"Archaedas Eroica - Fatigue Warlock",'',0,"HERO_07","id13");
insert into deck values (131,"GREENSHEEP’S TOP 10 LEGEND AGGRO SHAMAN (JUNE 2016, SEASON 27)",'',0,"HERO_02","id17");
insert into deck values (132,"Standard Malylock",'',0,"HERO_07","id14");
insert into deck values (133,"Duane\'s Zoolock",'',0,"HERO_07","id20");
insert into deck values (134,"DeerJason\'s Zoolock",'',0,"HERO_07","id4");
insert into deck values (135,"Rdu Yogg Tempo Mage - Dreamhack Summer 2016",'',0,"HERO_08","id7");
insert into deck values (136,"Hoej’s C’Thun Warrior DreamHack Summer 2016",'',0,"HERO_01","id16");
insert into deck values (137,"Zoo Warlock",'',0,"HERO_07","id9");
insert into deck values (138,"Freeze Mage Laughing Guida",'',0,"HERO_08","id3");
insert into deck values (139,"Elix Top100 Warlock Budget",'',0,"HERO_07","id13");
insert into deck values (140,"Pavlik Tempo Mage S27",'',0,"HERO_08","id10");
insert into deck values (141,"AKAWonder\'s C\'Thun Druid - Europe Spring Championship",'',0,"HERO_06","id7");
insert into deck values (142,"Thijs\' Aggro Shaman - Europe Spring Championship 2016",'',0,"HERO_02","id10");
insert into deck values (143,"Turna\'s Zoolock - Europe Spring Championships 2016",'',0,"HERO_07","id10");
insert into deck values (144,"Control Shaman",'',0,"HERO_02","id1");
insert into deck values (145,"war",'',0,"HERO_01","id15");
insert into deck values (146,"JAMBRE’S TOP 10 EU STANDARD SECRET PALADIN DECK",'',0,"HERO_04","id12");
insert into deck values (147,"fibbonacci n\'zoth warrior",'',0,"HERO_01","id7");
insert into deck values (148,"Hybrid Shaman - Guida completa Lik",'',0,"HERO_02","id4");
insert into deck values (149,"Ladro N\'zoth Control",'',0,"HERO_03","id20");
insert into deck values (150,"MidRange Mago eco",'',0,"HERO_08","id9");
insert into deck values (151,"Zalae’s (Team Archon) Deck Gauntlet 2 Patron Warrior",'',0,"HERO_01","id9");
insert into deck values (152,"Brian Kibler’s N’Zoth Dragon Paladin (May 2016)",'',0,"HERO_04","id17");
insert into deck values (153,"N\'Zoth Paladin - Dazzar",'',0,"HERO_04","id20");
insert into deck values (154,"Reno Dragon N\'Zoth Priest",'',0,"HERO_09","id16");
insert into deck values (155,"Aggro Shaman",'',0,"HERO_02","id3");
insert into deck values (156,"Cydonia’s Renolock – Hearthstone Americas Spring Prelims 2016",'',0,"HERO_07","id10");
insert into deck values (157,"CHAKKI’S BEAST DRUID – HEARTHSTONE AMERICAS SPRING PRELIMS 2016",'',0,"HERO_06","id12");
insert into deck values (158,"OTK PRIST",'',0,"HERO_09","id20");
insert into deck values (159,"N\'zoth Ladro",'',0,"HERO_03","id20");
insert into deck values (160,"Gaara\'s Priest - Europe Spring 2016",'',0,"HERO_09","id6");
insert into deck values (161,"Loyan\'s Warrior - Europe Spring 2016",'',0,"HERO_01","id13");
insert into deck values (162,"Pokrovac\'s Warlock - Europe Spring 2016",'',0,"HERO_07","id17");
insert into deck values (163,"Greensheep\'s Rogue - Europe Spring Preliminary 2016",'',0,"HERO_03","id19");
insert into deck values (164,"Xzirez’s Pirate Warrior – Hearthstone EU Spring Prelims 2016",'',0,"HERO_01","id12");
insert into deck values (165,"Ostkaka’s Leeroy Miracle Rogue – Hearthstone EU Spring Prelims 2016",'',0,"HERO_03","id1");
insert into deck values (166,"OTK worgen",'',0,"HERO_01","id6");
insert into deck values (167,"Super Budget Midrange Shaman",'',0,"HERO_02","id7");
insert into deck values (168,"Animated Mage by Dax (Standard S26)",'',0,"HERO_08","id9");
insert into deck values (169,"Thijs’ Aggro Divine Shield Paladin (Standard, May 2016, Season 26)",'',0,"HERO_04","id9");
insert into deck values (170,"Yogg-Saron Tempo Mage",'',0,"HERO_08","id20");
insert into deck values (171,"Firebat’s Season 26 (Standard) Aggro Warlock Zoo",'',0,"HERO_07","id19");
insert into deck values (172,"Zetalot Control Priest Volazj , N\'Zoth",'',0,"HERO_09","id15");
insert into deck values (173,"Aggro Shield Paladin by Ataraxy",'',0,"HERO_04","id10");
insert into deck values (174,"Reno C\'thun",'',0,"HERO_07","id9");
insert into deck values (175,"Laughing Freeze Mage S26",'',0,"HERO_08","id15");
insert into deck values (176,"Firebat’s MSI EGLX (Standard) Miracle Rogue",'',0,"HERO_03","id4");
insert into deck values (177,"Neobility’s MSI EGLX (Standard) Warlock Zoo",'',0,"HERO_07","id20");
insert into deck values (178,"GUGLY89 Ramp Druid 70% winrate",'',0,"HERO_06","id2");
insert into deck values (179,"Prelude’s MSI EGLX (Standard) Reno Jackson Warlock",'',0,"HERO_07","id8");
insert into deck values (180,"Amez Battle of the Best - Warrior",'',0,"HERO_01","id19");
insert into deck values (181,"Dragon Mage",'',0,"HERO_08","id10");
insert into deck values (182,"Beast Druid",'',0,"HERO_06","id17");
insert into deck values (183,"C\'thun patron warrior! 640Dust Low budget",'',0,"HERO_01","id15");
insert into deck values (184,"Trump - Druido - C\'Thun",'',0,"HERO_06","id10");
insert into deck values (185,"Frodan - Guerriero - Pirati",'',0,"HERO_01","id12");
insert into deck values (186,"Warrior C\'Thun Shield",'',0,"HERO_01","id18");
insert into deck values (187,"Pirata Warrior Standard Test",'',0,"HERO_01","id19");
insert into deck values (188,"Rogue Combo Standard Budget",'',0,"HERO_03","id4");
insert into deck values (189,"Sempok S25 Tuskarr Aggro Shaman Top5",'',0,"HERO_02","id18");
insert into deck values (190,"",'',0,"","id19");
